name: diff

on:
  pull_request:
    branches: [ master ]

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
      - name: Install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest

      - name: Benchmark
        run: go test -bench=^expr -benchmem -run=^$ -count=20 -timeout=30m | tee /tmp/new.txt

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Benchmark
        run: go test -bench=^expr -benchmem -run=^$ -count=20 -timeout=30m | tee /tmp/old.txt

      - name: Diff
        run: benchstat /tmp/old.txt /tmp/new.txt
